- id: pinned_update
  name: pinned_update
  entry: pinned_update
  language: python
  require_serial: true
  always_run: true

- id: meta
  name: meta
  entry: meta
  language: python
  require_serial: true
  always_run: true
