name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    environment: publish
    container: node:lts
    steps:
      - uses: actions/checkout@v3
      - name: "Workaround permissions issue"
        run: chown $(whoami):$(whoami) -R .
      - run: npm install @semantic-release/commit-analyzer
      - run: npm install @semantic-release/release-notes-generator
      - run: npm install @semantic-release/changelog
      - run: npm install @semantic-release/github
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
