name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    container: node:lts
    steps:
      - uses: actions/checkout@v3
      - run: npm install @semantic-release/github && npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
